name: Create release PR

on:
  push:
    branches:
      - release

jobs:
  # リリース用PRが既に存在するかどうかをチェック
  check-release-pr-exists:
    runs-on: ubuntu-latest
    outputs:
      pr_count: ${{ steps.check_pr_exitsts.outputs.test }}
    steps:
      - name: Check if pr exists
        id: check_pr_exitsts
        run: |
          echo "$(gh pr list -S 'Release to Main in:title' -B master | wc -l)" >> $GITHUB_OUTPUT
  create-release-pr:
    needs: check-release-pr-exists
    runs-on: ubuntu-latest
    # リリース用PRが既に存在する場合以下をスキップする
    if: ${{ needs.check-release-pr-exists.outputs.pr_count == 0 }}
    env:
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: bundle install
        run: |
          cd mobile && gem install bundler
          bundle install
      - name: Install dependencies
        # package.json に記載されている依存関係をインストール
        run: yarn
      - name: Version up
        run: |
          yarn version_up
      - name: Commit version_up files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "test ruby command"
          git push

      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: release
          GIT_PR_RELEASE_TEMPLATE: .github/pr_release_templete.erb
        run: |
          gem install -N git-pr-release
          git-pr-release --overwrite-description
