# releaseブランチマージ後、developブランチ向けのプルリクエストを作成する
# releaseプルリクのマージ後、delete branchをブラウザで実行しないように注意
# 厳密には、master宛のPRがマージされたらdevelopに対してPRを作成するので、release→masterのPRマージに限定しているわけではない
name: Create PR from release to develop

on:
  pull_request:
    branches:
      - not_found_branch
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: bundle install
        run: |
          cd mobile && gem install bundler
          bundle install

      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # master→developのPRを作成する
          GIT_PR_RELEASE_BRANCH_PRODUCTION: develop
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_TEMPLATE: .github/master_to_develop_pr_template.erb
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gem install -N git-pr-release
          git-pr-release --overwrite-description
