# releaseブランチマージ後、developブランチ向けのプルリクエストを作成する
# releaseプルリクのマージ後、delete branchをブラウザで実行しないように注意
name: Create PR from release to develop

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create release pr
        # head(-h)の指定をしないと、現在のブランチがheadになる
        # titleは要編集
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          gh pr create -B develop -H release -t "from release to develop" -b "test"
