name: Create release PR

on:
  push:
    branches:
      - release

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install dependencies
        # package.json に記載されている依存関係をインストール
        run: yarn
      - run: |
          yarn version_up
      - run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "test ruby command"
          git push

      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: release
          GIT_PR_RELEASE_TEMPLATE: .github/pull_request_template.erb
        run: |
          gem install -N git-pr-release
          git-pr-release --overwrite-description
